### ISSUE TITLE
Error response

### ISSUE THREAD

**Issue by sewek333** [Yirade/Carelink-Web#1]
website 
Error response
Error code: 404

Message: File not found.

Error code explanation: 404 - Nothing matches the given URI.

During installation, I receive an error: 'Could not find a version that satisfies the requirement (json, http.server, socketserver).' And another question, the country number, does it refer to codes like US, GR, etc.?

**Comment by Yirade** [comment]
Hey there!

Great news! We've fixed the issue reported on the website. Here's what's changed:

1. Installation Error:
You won't face any more trouble during installation. We've resolved the problem, and now you should be able to install the necessary packages smoothly.

2. Country Codes:
Yep, the "country number" refers to that cool two-letter country code like US for the United States and GR for Greece. Feel free to use this code when setting up your configuration.

Thanks a bunch for letting us know about this hiccup. If you have more questions or run into anything else, don't hesitate to reach out. I'm here to help!

Best regards,
Yirade

**Comment by Yirade** [comment]
Hey there! 🎉

Great news! We've fixed the issue reported on the website. Here's what's changed:

🛠️ Installation Error:
You won't face any more trouble during installation. We've resolved the problem, and now you should be able to install the necessary packages smoothly.

🌍 Country Codes:
Yep, the "country number" refers to that cool two-letter country code like US for the United States and GR for Greece. Feel free to use this code when setting up your configuration.

Thanks a bunch for letting us know about this hiccup. If you have more questions or run into anything else, don't hesitate to reach out. I'm here to help!

Best regards,
Yirade
